### ISSUE TITLE
DOCK3.8 source code

### ISSUE THREAD

**Issue by baltruke** [docking-org/pydock3#33]
Hi, 
I was following wiki tutorial about installation of DOCK3.8, but the following repository is not available:
git clone https://github.com/docking-org/DOCK.git
Could you tell me where to find fortan code of DOCK3.8?

**Comment by ianscottknight** [comment]
@hannabalt Yes, you can find the Fortran source code for DOCK at [https://github.com/docking-org/dock3](https://github.com/docking-org/dock3)

We will update relevant documentation to address this. Thanks!

**Comment by baltruke** [comment]
@ianscottknight thank you for the quick answer! I was trying to clone this repository https://github.com/docking-org/dock3, but it wasn't found.. Could you check if it actually available on your end, maybe it is only my problem? Thank you a lot in advance!

**Comment by ianscottknight** [comment]
@hannabalt If you don't have access to private repositories in docking-org, then you can apply for an academic license [here](https://dock.compbio.ucsf.edu/Online_Licensing/dock_license_application.html) and obtain a distribution of DOCK 3.8, which includes the Fortran source code for DOCK.
